### ISSUE TITLE
Try imagemagick

### ISSUE THREAD

**Issue by wchaws** [wchaws/serverless-image-handler#58]
**Is your feature request related to a problem? Please describe.**

imagemagick has much more features support than sharpjs. such as gif

https://imagemagick.org/index.php
https://www.npmjs.com/package/gm
https://serverless.pub/lambda-utility-layers/ 

**Describe the feature you'd like**

**Additional context**

**Comment by wchaws** [comment]
## Performance
sharp is 3x faster than imagemagick.

```
$ cd source/new-image-handler/
$ yarn run benchmark
yarn run v1.22.17
$ ts-node test/bench/perf.ts
sharp 9.04 ms 110.57 ops/sec 86 samples
imagemagick 28.2 ms 35.46 ops/sec 68 samples
Fastest is sharp
Done in 14.32s.
```

## Issues

if we embed imagemagick binary https://github.com/ImageMagick/ImageMagick/releases/download/7.1.0-16/ImageMagick-03b1a2e-gcc-x86_64.AppImage into lambda layer.  It will raise `EPIPE` error

```
{
    "errorType": "Error",
    "errorMessage": "write EPIPE",
    "code": "EPIPE",
    "errno": "EPIPE",
    "syscall": "write",
    "stack": [
        "Error: write EPIPE",
        "    at afterWriteDispatched (internal/stream_base_commons.js:156:25)",
        "    at writeGeneric (internal/stream_base_commons.js:147:3)",
        "    at Socket._writeGeneric (net.js:787:11)",
        "    at Socket._write (net.js:799:8)",
        "    at doWrite (_stream_writable.js:403:12)",
        "    at writeOrBuffer (_stream_writable.js:387:5)",
        "    at Socket.Writable.write (_stream_writable.js:318:11)",
        "    at Readable.ondata (_stream_readable.js:718:22)",
        "    at Readable.emit (events.js:314:20)",
        "    at Readable.EventEmitter.emit (domain.js:483:12)"
    ]
}
```
